### ISSUE TITLE
menuOnTap is not being called when using context menu to block video.

### ISSUE THREAD

**Issue by rain1** [josephcrowell/youtube-content-blocker#1]
**What version of this package are you using?**
0.4.2

**What operating system, Node.js, and npm version?**
Win 10 Node 12.18.3
> node -v
v12.18.3

**What happened?**
When watching video and I click 3 dots and then Block Video, no error is logged in console and video was not blocked, menuOnTap was not even called. This is the function where `const player = window["ytInitialPlayerResponse"];` was called initially. This part was called before initial fix. Now the entire function itself is not even called. Looking at event handlers some https://www.youtube.com/s/desktop/494dd881/jsbin/custom-elements-es5-adapter.vflset/custom-elements-es5-adapter.js seems to handle click event for that. 

**What did you expect to happen?**
menuOnTap to be called from inject.js

**Are you willing to submit a pull request to fix this bug?**
No.

Off topic: some scripts use tabs instead spaces. Didn't feel like making separate ticket for that but let's have uniform style for entire project.

**Comment by josephcrowell** [comment]
Looks like jupiter's manifest v3 fix broke the seeder

**Comment by josephcrowell** [comment]
Ok, marking this issue as closed then. Talk to you later.
